apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: base
spec:
  releaseName: istio-base
  chart:
    spec:
      chart: base
      version: "1.25.1"
      sourceRef:
        kind: HelmRepository
        name: istio 
  interval: 5m 
  install:
    remediation:
      retries: 3
