apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-cni
spec:
  interval: 5m
  chart:
    spec:
      chart: cni
      sourceRef:
        kind: HelmRepository
        name: istio
  values:
    _internal_defaults_do_not_set:
      hub: ""
      tag: ""
      variant: ""
      image: install-cni
      pullPolicy: ""

      logging:
        level: ""


      cniBinDir: /opt/cni/bin
      cniConfDir: /etc/cni/net.d
      cniConfFileName: ""
      cniNetnsDir: "/var/run/netns"

      excludeNamespaces:
        - kube-system

      affinity: {}

      podAnnotations: {}

      chained: true

      provider: "default"

      ambient:
        enabled: true
        configDir: ""
        dnsCapture: true
        ipv6: true
        reconcileIptablesOnStartup: true


      repair:
        enabled: true
        hub: ""
        tag: ""


        labelPods: false
        deletePods: false
        repairPods: true

        initContainerName: "istio-validation"

        brokenPodLabelKey: "cni.istio.io/uninitialized"
        brokenPodLabelValue: "true"

      seccompProfile: {}

      seLinuxOptions: {}

      resources:
        requests:
          cpu: 100m
          memory: 100Mi

      resourceQuotas:
        enabled: false
        pods: 5000

      rollingMaxUnavailable: 1

      revision: ""

      ownerName: ""

      global:
        hub: docker.io/istio

        tag: 1.25.1

        variant: ""

        imagePullPolicy: ""

        logging:
          level: info

        logAsJson: false

        imagePullSecrets: []

        defaultResources:
          requests:
            cpu: 100m
            memory: 100Mi

      env: {}
