apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-cni
spec:
  releaseName: istio-cni
  interval: 5m
  chart:
    spec:
      chart: cni
      version: "1.25.1"
      sourceRef:
        kind: HelmRepository
        name: istio
  install:
    remediation:
      retries: 3