apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-cni
spec:
  releaseName: istio-cni
  interval: 5m
  chart:
    spec:
      chart: cni
      sourceRef:
        kind: HelmRepository
        name: istio
  install:
    remediation:
      retries: 3
  values:
    global:
      ambient:
        enabled: true