apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
spec:
  releaseName: istio-base
  interval: 5m
  chart:
    spec:
      chart: istio/base
      version: "1.1.0"
      sourceRef:
        kind: HelmRepository
        name: istio
  install:
    remediation:
      retries: 3