apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
spec:
  releaseName: istiod
  chart:
    spec:
      chart: istiod
      version: "1.25.1"
      sourceRef:
        kind: HelmRepository
        name: istio 
  interval: 5m 
  install:
    remediation:
      retries: 3
  values:
    ambient:
      enabled: true
    # ambientConfig:
    #   reconcileIPtablesOnStartup: true
    #   dnsCapture: true
    #   ipv6: true
    pilot:
      enabled: true
      env:
        PILOT_ENABLE_AMBIENT: "true"
    # global:
    #   proxy:
    #     enabled: true
