apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-cni
spec:
  interval: 5m
  chart:
    spec:
      chart: cni
      sourceRef:
        kind: HelmRepository
        name: istio
  values:
    _internal_defaults_do_not_set:
      ambient:
        enabled: true