apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - istio-namespace.yaml
  - istio-repo.yaml
  - istio-base-helmrelease.yaml
  - istiod-helmrelease.yaml
namespace: istio-system
