apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airflow
spec:
  releaseName: airflow
  chart:
    spec:
      chart: airflow
      version: "1.16.0"
      sourceRef:
        kind: HelmRepository
        name: apache-airflow 
  interval: 5m 
  install:
    remediation:
      retries: 3