apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
spec:
  releaseName: kyverno
  chart:
    spec:
      chart: kyverno
      version: "3.3.7"
      sourceRef:
        kind: HelmRepository
        name: kyverno 
  interval: 5m 
  install:
    remediation:
      retries: 3
    createNamespace: true