apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio
spec:
  releaseName: istio
  chart:
    spec:
      chart: istio
      version: "1.1.0"
      sourceRef:
        kind: HelmRepository
        name: istio 
  interval: 5m 
  install:
    remediation:
      retries: 3
